### PR TITLE
remove exception "ConcurrentModificationError"

### PR DESCRIPTION
**Pull request by AlexeyYuPopkov**
"ConcurrentModificationError (Concurrent modification during iteration: Instance of '_HashSet<Module>'.)"

### CODE REVIEW

**Comment by pese-git** [comment]
How to reproduce this error?

**Comment by AlexeyYuPopkov** [comment]
> How to reproduce this error?

reproducing when use the public method dropModules.

**Comment by pese-git** [comment]
Please provide an example in which the error is reproduced

**Comment by AlexeyYuPopkov** [comment]
> Please provide an example in which the error is reproduced

Снимок экрана 2023-01-06 в 16 51 13

**Comment by AlexeyYuPopkov** [comment]
> > Please provide an example in which the error is reproduced

> Снимок экрана 2023-01-06 в 16 51 13

**Wrong:**
`set1.removeAll(set1);`
**Right:**
` set1.clear();`
`set1.removeAll({...set1});`

**Review by pese-git — COMMENTED** [review]
@AlexeyYuPopkov Thank you for this fix :)

**Pull request closed without merging**
